ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER rachida IDENTIFIED BY MySecurePass123;

GRANT CONNECT, RESOURCE TO rachida;

GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE TO rachida;

ALTER USER rachida DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

