name: Test GraalPy Micronaut Pygal Charts
on:
  push:
    paths:
      - 'graalpy/graalpy-micronaut-pygal-charts/**'
      - '.github/workflows/graalpy-micronaut-pygal-charts.yml'
  pull_request:
    paths:
      - 'graalpy/graalpy-micronaut-pygal-charts/**'
      - '.github/workflows/graalpy-micronaut-pygal-charts.yml'
  workflow_dispatch:
permissions:
  contents: read
env:
  NATIVE_IMAGE_OPTIONS: '-J-Xmx16g'
jobs:
  run:
    name: 'graalpy-micronaut-pygal-charts'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24.0.1'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
          native-image-job-reports: 'true'
      - name: Build, test, and run 'graalpy-micronaut-pygal-charts' using Maven
        run: |
          cd graalpy/graalpy-micronaut-pygal-charts
          ./mvnw --no-transfer-progress clean test -Dmicronaut.http.client.read-timeout=1m
          ./mvnw --no-transfer-progress mn:run &
          mnpid="$!"
          sleep 30
          curl --fail-with-body --fail-with-body --silent --dump-header - -o /dev/null http://localhost:8080/java
          kill $mnpid
      - name: Build and run native 'graalpy-micronaut-pygal-charts' using Maven
        run: |
          cd graalpy/graalpy-micronaut-pygal-charts
          ./mvnw --no-transfer-progress clean package -DskipTests -Dpackaging=native-image
          ./target/demo &
          mnpid="$!"
          sleep 20
          curl --fail-with-body --fail-with-body --silent --dump-header - -o /dev/null http://localhost:8080/python
          kill $mnpid
