name: Test GraalPy Scripts Guide
on:
  push:
    paths:
      - 'graalpy/graalpy-scripts-debug/**'
      - '.github/workflows/graalpy-scripts-debug.yml'
  pull_request:
    paths:
      - 'graalpy/graalpy-scripts-debug/**'
      - '.github/workflows/graalpy-scripts-debug.yml'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run:
    name: 'graalpy-scripts-debug'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: graalvm/setup-graalvm@27b360dbb857524eaf0b4c4cef364d38e5b4f173 # v1.6.7
        with:
          version: '25.4'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'
      - name: Build, test, and run 'graalpy-scripts-debug' using Maven
        run: |
          cd graalpy/graalpy-scripts-debug
          ./mvnw --no-transfer-progress test
      - name: Build, test, and run 'graalpy-scripts-debug' using Gradle
        run: |
          cd graalpy/graalpy-scripts-debug
          ./gradlew test
